version: "3.6"
services:
  mage:
    image: mage
    container_name: mage
    ports:
      - 6789:6789
    environment:
      - GCP_PROJECT_ID=${PROJECT_ID}
    restart: always
  
  dashboard:
    image: dashboard
    container_name: dashboard
    ports:
      - 8501:8501
    environment:
      - GCP_PROJECT_ID=${PROJECT_ID}
    restart: always
